### PR TITLE
Simple Fix

### PR DESCRIPTION
**Pull request by IamSanjid**
This is just a simple fix for stuck at loading map when relog.

### CODE REVIEW

**Comment by holly-hacker** [comment]
Did you actually test this? Every time you download a map, it will be brand new, unedited data, so your caching code would only break stuff.

**Comment by IamSanjid** [comment]
Well yes I did and it worked idk why in my case it just get stuck but when I used those codes it was ok for me. And somehow in my case, it is getting the old maps data.

**Comment by holly-hacker** [comment]
I don't see why this would work then. Please debug the actual issue and fix that if it is a problem.

Also, why are you keeping all the downloaded MapData in memory? You're not using it anywhere, it will just take up more and more RAM over time.

**Comment by IamSanjid** [comment]
Well sorry for that I just copied my HandlerMap I used that for myself somewhere else you can just edit the file.

**Pull request closed without merging**
